CREATE TABLE Users (
	ID INT PRIMARY KEY IDENTITY(1, 1),
	Name NVARCHAR(100) NOT NULL,
	Email NVARCHAR(100) UNIQUE NOT NULL,
	RegistrationDate DATE DEFAULT GETDATE()
);

CREATE TABLE Products (
	ID INT PRIMARY KEY IDENTITY(1, 1),
	Name NVARCHAR(100) NOT NULL,
	Category NVARCHAR(100) NOT NULL,
	Price DECIMAL(10, 2)
);

CREATE TABLE Orders (
	ID INT PRIMARY KEY IDENTITY(1, 1),
	UserID INT FOREIGN KEY (UserID) REFERENCES Users(ID),
	ProductID INT FOREIGN KEY (ProductID) REFERENCES Products(ID),
	Quantity INT,
	OrderDate DATE DEFAULT GETDATE()
);